language: php

php:
  - 8.0
  - 8.1
  - nightly

env:
  - XDEBUG_MODE=coverage

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
install:
  - composer i -n -o --no-suggest --prefer-dist
  - composer req php-coveralls/php-coveralls -n -o --no-suggest --prefer-dist

script:
  - composer test:travis

after_success:
  - travis_retry php vendor/bin/php-coveralls -v --coverage_clover=tests/output/clover.xml --json_path=tests/output/coveralls.json

cache:
  directories:
    - $HOME/.composer/cache
