language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
install:
  - composer i -n -o --no-suggest --prefer-dist

script:
  - composer test

cache:
  directories:
    - $HOME/.composer/cache
